= bonding

This role will create machine config files to setup ethernet bonding on cluster nodes. This can easily be modified to directly apply these machine configs, however it is often preferred to add these machine configs at install time so writing to a file for injecting into install manifests was the goal here.

The files it creates on the node are a NetworkManager config file, script that builds bonding configuration at run time, and a systemd unit file that runs at boot time that calls the script.

The main reason we don't just build the network config files locally and add them directly inside the machine config is that we don't have access to the MAC addresses of the network cards on the node to set the DHCP_CLIENT_ID in the config file.

`Why do we need that?`

Simple, the bond device will by default send the MAC address of the active network card which often changes on boot. This will interfere with your DHCP host assigning the same IP to your nodes on reboot if you setup bonding and do not tell the bond device to always send the same MAC address.

== Requirements

- Appropriate variables setup in playbook
- A configuration file to pass with bonding settings


== Role Variables

See `Example Playbook` below for more specific details on global vars. At a high level, the following variables need to be defined:

- **Passed as extra var or environment variable**
  * `config`: The json config file that holds the bonding details
  * `destination`: Where to create the machine config files (-e destination=./out)
  * `type`: [OPTIONAL] The type of node to create machine configs for, default is all

NOTE: The `type` variable corresponds to the parent keys in the config file passed. The key is the nodes node role (master, worker, etc...) as defined in the cluster.

== Dependencies

The following python modules are required:

----
Jinja2
----


== Example config file

----
{
  "master": {
    "block_storage_vlan_parent_iface": "bond0",
    "block_storage_vlan_id": "1305",
    "block_storage_mtu": "9000",
    "bonding": {
        "bond-0": {
          "name": "bond0",
          "interfaces": "ens1f0,ens1f1",
          "bootproto": "dhcp",
          "mtu": "1500",
          "options": "mode=802.3ad,miimon=500"
      },
      "bond-1": {
          "name": "bond1",
          "interfaces": "ens3f0,ens3f1",
          "mtu": "9000",
          "bootproto": "dhcp",
          "options": "mode=active-backup,miimon=100,updelay=500,downdelay=1000,arp_interval=500,primary=ens1f0"
      }
    }
  },
  "worker": {
    "block_storage_vlan_parent_iface": "bond0",
    "block_storage_vlan_id": "1305",
    "block_storage_mtu": "9000",
    "bonding": {
        "bond-0": {
          "name": "bond0",
          "interfaces": "ens1f0,ens1f1",
          "bootproto": "dhcp",
          "mtu": "1500",
          "options": "mode=802.3ad,miimon=500"
      },
      "bond-1": {
          "name": "bond1",
          "interfaces": "ens3f0,ens3f1",
          "mtu": "9000",
          "bootproto": "dhcp",
          "options": "mode=active-backup,miimon=100,updelay=500,downdelay=1000,arp_interval=500,primary=ens1f0"
      }
    }
  }
}
----

== Example Playbook
----
---
- hosts: localhost
  tasks:
  - name: Set do_all var if type is not set
    set_fact:
      do_all: true
    when: type is not defined

  - name: Fail if config is undefined
    fail:
      msg: "You need to define a config file with -e 'config=<json file>' to run this playbook."
    failed_when: config is not defined

  - name: Fail if destination is undefined
    fail:
      msg: "You need to define destination with -e 'destination=<path to generate files>' to run this playbook."
    failed_when: destination is not defined

  - name: Create single node type bonding config
    include_role:
        name: bonding
    when: type is defined

  - name: Create all node type bonding configs
    include_role:
      name: bonding
    vars:
      jsonconf: "{{lookup('file', config)}}"
      type: "{{line_item}}"
    with_items: "{{ jsonconf.keys()|list }}"
    loop_control:
      loop_var: line_item
    when: do_all is defined
----

== Running the example playbook

This example playbook requires a destination folder to build machine configs in, and a json config file the describes the nodes types (matching the node labels for role) to configure bonding on and the bonding configurations.

TIP: The playbook must define all required variables or you can pass them as extra vars on the command line. Either way, the role will will fail without these variables set.

.Example run
----
ansible-playbook -e destination=./out -e config=./config.json main.yml
----

== License

Apache License 2.0

== Author Information

mailto:ddreggor@redhat.com[David Dreggors] <ddreggor@redhat.com>
